title: 조금이라도 더 나아지고 싶어요.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Yaejin # add your name
author-img: snoopy.jpg # add your photo
about-author: 아직은 아무것도 모르겠지만 그래도 조금씩 나아지고 있다고 믿어요.  # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: yaejinha # add your Github handle
social-linkedin: yaejinha # add your Linkedin handle
social-email: yaejinha@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
